apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rhtas-demo-dev

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

images:
  - name: quay.io/acme/rhtas-hello-world
    newName: quay.io/acme/rhtas-hello-world
    newTag: placeholder-0

commonLabels:
  app.kubernetes.io/name: hello-world
  app.kubernetes.io/part-of: rhtas-cosign-demos
