apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rhtas-demo-dev

resources:
  - namespace.yaml
  - trust-configmap.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

images:
  - name: quay.io/rhn_support_jeretan/hello-world-cosign
    newName: quay.io/rhn_support_jeretan/hello-world-cosign
    newTag: placeholder-0

labels:
  app.kubernetes.io/name: hello-world
  app.kubernetes.io/part-of: rhtas-cosign-demos
