apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-trust
  labels:
    app: hello-world
data:
  # Populated/updated by CI or operators for the live demo. Defaults are placeholders.
  SCENARIO: "tekton"
  BUILD_VERSION: "tekton-rhtas-hello-world-run-2zmbd"
  IMAGE_REF: "quay.io/rhn_support_jeretan/hello-world-cosign:tekton-4ada0952-32f1-451d-9878-c6a93763649c"
  IMAGE_DIGEST: "sha256:d59763b38aac8851dbb5ab8533284c2a68a9ad3de74b99990f6a3d9a48007056"
  SIGNER_IDENTITY: "https://kubernetes.io/namespaces/openshift-pipelines/serviceaccounts/tekton-chains-controller"
  SIGNED_AT: "2026-07-31T08:12:42Z"
  FULCIO_URL: "https://fulcio-server-trusted-artifact-signer.apps.cluster-7s4dl.dyn.redhatworkshops.io"
  REKOR_URL: "https://rekor-server-trusted-artifact-signer.apps.cluster-7s4dl.dyn.redhatworkshops.io"
  OIDC_ISSUER: "https://kubernetes.default.svc"
  GIT_COMMIT: "unknown"
  BUILDER_IMAGE: "registry.access.redhat.com/ubi9/openjdk-21:1.21"
  RUNTIME_IMAGE: "registry.access.redhat.com/hi/openjdk:21.0.11-runtime"
  TUF_URL: "https://tuf-trusted-artifact-signer.apps.cluster-7s4dl.dyn.redhatworkshops.io"
  COSIGN_IMAGE: "registry.access.redhat.com/hi/cosign:3.1.1"
