apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: rhtas-hello-world-spiffe
  namespace: rhtas-demo-ci
  labels:
    rhtas.demo/scenario: spiffe
spec:
  params:
    - name: quay-org
      type: string
    - name: quay-repo
      type: string
      default: rhtas-hello-world
  workspaces:
    - name: shared-workspace
    - name: docker-credentials
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: https://github.com/acme/rhtas-cosign-openshift-demos.git

    - name: maven-build
      runAfter: [fetch-source]
      taskRef:
        name: maven-build
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: sast
      runAfter: [maven-build]
      taskRef:
        name: sast-semgrep
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: build-push
      runAfter: [sast]
      taskRef:
        name: buildah-push
      serviceAccountName: spiffe-cosign-signer
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: dockerconfig
          workspace: docker-credentials
      params:
        - name: IMAGE
          value: quay.io/$(params.quay-org)/$(params.quay-repo):spiffe-$(context.pipelineRun.uid)
        - name: BUILD_VERSION
          value: spiffe-$(context.pipelineRun.name)

    - name: spiffe-sign
      runAfter: [build-push]
      taskRef:
        name: spiffe-cosign-sign
      serviceAccountName: spiffe-cosign-signer
      workspaces:
        - name: dockerconfig
          workspace: docker-credentials
      params:
        - name: IMAGE
          value: quay.io/$(params.quay-org)/$(params.quay-repo):spiffe-$(context.pipelineRun.uid)
      # Pod template label required for ClusterSPIFFEID selector
      podTemplate:
        labels:
          rhtas.demo/signer: "true"
