apiVersion: v1
kind: ServiceAccount
metadata:
  name: spiffe-cosign-signer
  namespace: rhtas-demo-ci
  labels:
    rhtas.demo/signer: "true"
secrets:
  - name: quay-credentials
imagePullSecrets:
  - name: quay-credentials
