apiVersion: v1
kind: ServiceAccount
metadata:
  name: rhtas-signer
  namespace: rhtas-demo-ci
  labels:
    app.kubernetes.io/name: rhtas-signer
    app.kubernetes.io/component: cosign-robot
  annotations:
    description: >
      Robot account for Jenkins cosign keyless signing.
      Fulcio identity: https://kubernetes.io/namespaces/rhtas-demo-ci/serviceaccounts/rhtas-signer
